### ISSUE TITLE
Can I has code please?

### ISSUE THREAD

**Issue by Yanall-Boutros** [hahamyt/scc#1]
Hi. I see this project was uploaded recently. I understand it's early, but are there plans to release the code for the accompanying paper?

https://arxiv.org/pdf/2405.04009

**Comment by hahamyt** [comment]
Thank you for your attention. Once our submission undergoes review, the code will be made public as soon as possible

**Comment by hahamyt** [comment]
I released the core code, more details will be updated in the future, thanks for your attention
